galaxy_info:
  author: Adrian Likins
  description: mcgee_role1 from collection_mcgee from collection_multi_one_git_repo
  company: er, thats complicated

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: GPLv2

  galaxy_tags: []

dependencies: []
